#log_level = "debug"         # uncomment and change to adjust log level (see help).
#clear_input = true          # uncomment have input cleared on enter.
#disable_local_echo = true   # uncomment to disable displaying input commands in output.
